namespace FurnitureStore.Application.Common.Interfaces;

/// <summary>A stored file and the public URL it is served from.</summary>
public sealed record StoredFile(string Url, string FileName, long SizeBytes, string ContentType);

/// <summary>
/// Stores uploaded files. The MVP writes to wwwroot/uploads; a cloud implementation (Azure Blob, S3)
/// can be swapped in without touching callers.
/// </summary>
public interface IFileStorageService
{
    /// <summary>
    /// Validates and stores an image. The stored name is generated by the server; the client file name
    /// is only used to read the extension. Throws AppValidationException when the file is not an allowed image.
    /// </summary>
    Task<StoredFile> SaveImageAsync(Stream content, string originalFileName, string folder, CancellationToken cancellationToken = default);

    /// <summary>Deletes a file previously returned by this service. Unknown or external URLs are ignored.</summary>
    Task DeleteAsync(string? url, CancellationToken cancellationToken = default);
}
