using FurnitureStore.Application.Common.Media;

namespace FurnitureStore.Application.Common.Interfaces;

/// <summary>A stored file and the public URL it is served from.</summary>
/// <param name="Width">Pixel size of a stored picture, when the storage knows it (for width / height attributes).</param>
public sealed record StoredFile(string Url, string FileName, long SizeBytes, string ContentType, int? Width = null, int? Height = null);

/// <summary>
/// Stores uploaded files. The MVP writes to wwwroot/uploads; a cloud implementation (Azure Blob, S3)
/// can be swapped in without touching callers.
/// </summary>
public interface IFileStorageService
{
    /// <summary>
    /// Validates an uploaded picture and stores it resized for where it is shown (<paramref name="preset"/>), with its
    /// smaller copies. The stored name is generated by the server; the client file name is only used to read the
    /// extension. Returns the largest copy. Throws AppValidationException when the file is not an acceptable picture.
    /// </summary>
    Task<StoredFile> SaveImageAsync(Stream content, string originalFileName, ImagePreset preset, CancellationToken cancellationToken = default);

    /// <summary>Deletes a file previously returned by this service, with its smaller copies. Unknown or external URLs are ignored.</summary>
    Task DeleteAsync(string? url, CancellationToken cancellationToken = default);
}
